// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: proto/wallet.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "wallet";

export interface FilterWalletRequest {
  userId: string;
  currency: string;
}

export interface CreateWalletRequest {
  userId: string;
  currency: string;
}

export interface UpdateWalletRequest {
  userId: string;
  currency: string;
  amount: number;
  type: string;
}

export interface CreateWalletResponse {
  id: string;
  userId: string;
  currency: string;
  balance: number;
}

export const WALLET_PACKAGE_NAME = "wallet";

export interface WalletServiceClient {
  createWallet(request: CreateWalletRequest): Observable<CreateWalletResponse>;

  getTradeWallet(request: FilterWalletRequest): Observable<CreateWalletResponse>;

  trade(request: UpdateWalletRequest): Observable<CreateWalletResponse>;
}

export interface WalletServiceController {
  createWallet(
    request: CreateWalletRequest,
  ): Promise<CreateWalletResponse> | Observable<CreateWalletResponse> | CreateWalletResponse;

  getTradeWallet(
    request: FilterWalletRequest,
  ): Promise<CreateWalletResponse> | Observable<CreateWalletResponse> | CreateWalletResponse;

  trade(
    request: UpdateWalletRequest,
  ): Promise<CreateWalletResponse> | Observable<CreateWalletResponse> | CreateWalletResponse;
}

export function WalletServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createWallet", "getTradeWallet", "trade"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("WalletService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("WalletService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const WALLET_SERVICE_NAME = "WalletService";
