services:
  postgres:
    image: postgres
    container_name: forex_postgres
    environment:
      POSTGRES_PASSWORD: forex_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgres_data:
