name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Debug pnpm path
        run: which pnpm

      - name: Debug pnpm cache
        run: sh -c "echo 'pnpm cache directory: $(pnpm store path)'"

      - name: Clear pnpm cache
        run: pnpm store prune

      - name: Setup protoc
        uses: arduino/setup-protoc@v3.0.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t lint test build
